# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'test/**/*'
    - 'rack-protection/**/*'
    - 'sinatra-contrib/**/*'

# Temporary allow single line methods
Style/SingleLineMethods:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/ClassVars:
  Enabled: false
